apiVersion: v1
kind: ConfigMap
metadata:
  name: sosa-config
data:
  # kv format
  key: "value"
  $actual-config-file$: "name.properties"

  # file format
  name.properties: |
    field=value1,value2
