spring:
  application:
    name: sosa-worker-init

  main:
    web-application-type: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # Recommended for publishers:
    publisher-confirm-type: correlated
    publisher-returns: true
