spring:
  application:
    name: sosa-worker-init

  main:
    web-application-type: none

  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # Recommended for publishers:
    publisher-confirm-type: correlated
    publisher-returns: true

    listener:
      simple:
        prefetch: 1
      direct:
        prefetch: 1