apiVersion: v1
kind: Service
metadata:
  name: chesstango-rabbit-svc
spec:
  selector:
    app: chesstango-rabbit
  ports:
    - name: rabbit
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbit-management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chesstango-rabbit
  labels:
    app: chesstango-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chesstango-rabbit
  template:
    metadata:
      name: chesstango-rabbit
      labels:
        app: chesstango-rabbit
    spec:
      containers:
        - name: chesstango-rabbit
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_password
      restartPolicy: Always
      