apiVersion: apps/v1
kind: Deployment
metadata:
  name: chesstango-rabbit
  labels:
    app: chesstango-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chesstango-rabbit
  template:
    metadata:
      name: chesstango-rabbit
      labels:
        app: chesstango-rabbit
    spec:
      containers:
        - name: chesstango-rabbit
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
      restartPolicy: Always
      