apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosa-worker
  labels:
    app: sosa-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sosa-worker
  template:
    metadata:
      name: sosa-worker
      labels:
        app: sosa-worker
    spec:
      containers:
        - name: sosa-worker
          image: sosa-worker:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBIT_HOST
              value: "chesstango-rabbit-svc.default.svc.cluster.local"
      restartPolicy: Always